version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
    - checkout
    - run: pyenv global 3.10.5
    - run: pip install djlint
    - run: djlint --profile=jinja KiraDJLint__Ignore-H006-inside-div--H006.html
